services:
  postgres:
    image: ankane/pgvector:latest
    container_name: business_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql

  app:
    build: .
    container_name: business_api
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:strongpassword@postgres:5432/business_directory
      PYTHONPATH: "/app"  # Ensure Python recognizes /app as a module
    env_file:
      - .env  # Load env variables
    volumes:
      - ./app:/app
    working_dir: /app  # Ensures FastAPI runs from the correct directory
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:
